name: Android Segment Release
on:
  push:
    branches:
      - release-build
env:
  # Keep original variable names for Gradle compatibility, but use new Portal credentials
  OSSRH_USERNAME: "${{ secrets.MAVEN_CENTRAL_USERNAME }}"
  OSSRH_PASSWORD: "${{ secrets.MAVEN_CENTRAL_TOKEN }}"
  # Temporary: Keep for compatibility until publish-mavencentral.gradle is updated
  SONATYPE_STAGING_PROFILE_ID: ""
  SIGNING_KEY: "${{ secrets.GPG_KEY_CONTENTS_BASE64 }}"
  KEY_ID: "${{ secrets.SIGNING_KEY_ID }}"
  KEY_PASSWORD: "${{ secrets.SIGNING_PASSWORD }}"
  KEY_RING_FILE: "secret.kbx"
  TAG_NAME: "${{ github.ref_name }}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Download Dependencies
      run: ./gradlew androidDependencies
    - name: Build Destination
      run: ./gradlew clean :destination:build
    - name: Add Maven Central signing key
      run: base64 -d <<< ${{ env.SIGNING_KEY }} > destination/${{ env.KEY_RING_FILE }}
    - name: Build and publish to Maven Central Portal
      run: |
        echo "Building and signing artifacts..."
        ./gradlew :destination:publishReleasePublicationToMavenLocal --info
        
        echo "Finding published artifacts..."
        # Find the actual location of published artifacts
        PUBLISHED_POM=$(find $HOME/.m2/repository -name "*segment-analytics-kotlin-destination*.pom" -type f | head -1)
        
        if [ -z "$PUBLISHED_POM" ]; then
          echo "ERROR: No published POM file found!"
          echo "Searching for any POM files in local repository:"
          find $HOME/.m2/repository -name "*.pom" -type f | head -10
          exit 1
        fi
        
        echo "Found POM at: $PUBLISHED_POM"
        ARTIFACT_SOURCE_DIR=$(dirname "$PUBLISHED_POM")
        echo "Artifact directory: $ARTIFACT_SOURCE_DIR"
        
        # List what files are actually available
        echo "Available files in artifact directory:"
        ls -la "$ARTIFACT_SOURCE_DIR"
        
        # Extract version and artifact info from the path
        VERSION=$(basename "$(dirname "$ARTIFACT_SOURCE_DIR")")
        ARTIFACT_ID=$(basename "$(dirname "$(dirname "$ARTIFACT_SOURCE_DIR")")")
        GROUP_PATH=$(dirname "$(dirname "$(dirname "$ARTIFACT_SOURCE_DIR")")" | sed "s|$HOME/.m2/repository/||")
        
        echo "Detected - Group: $GROUP_PATH, Artifact: $ARTIFACT_ID, Version: $VERSION"
        
        echo "Creating properly structured bundle for Portal upload..."
        # Create temporary directory with proper Maven structure
        BUNDLE_DIR="/tmp/maven-bundle"
        ARTIFACT_DIR="$BUNDLE_DIR/$GROUP_PATH/$ARTIFACT_ID/$VERSION"
        mkdir -p "$ARTIFACT_DIR"
        
        # Copy all available artifacts
        echo "Copying artifacts..."
        cp "$ARTIFACT_SOURCE_DIR"/*.pom "$ARTIFACT_DIR/" 2>/dev/null || echo "No POM files found"
        cp "$ARTIFACT_SOURCE_DIR"/*.aar "$ARTIFACT_DIR/" 2>/dev/null || echo "No AAR files found"
        cp "$ARTIFACT_SOURCE_DIR"/*.jar "$ARTIFACT_DIR/" 2>/dev/null || echo "No JAR files found"
        cp "$ARTIFACT_SOURCE_DIR"/*.asc "$ARTIFACT_DIR/" 2>/dev/null || echo "No signature files found"
        
        # Copy existing checksums if they exist, otherwise generate them
        cp "$ARTIFACT_SOURCE_DIR"/*.md5 "$ARTIFACT_DIR/" 2>/dev/null || echo "No existing MD5 files"
        cp "$ARTIFACT_SOURCE_DIR"/*.sha1 "$ARTIFACT_DIR/" 2>/dev/null || echo "No existing SHA1 files"
        
        # Generate missing checksums
        cd "$ARTIFACT_DIR"
        for file in *.pom *.aar *.jar; do
          if [ -f "$file" ]; then
            if [ ! -f "$file.md5" ]; then
              echo "Generating MD5 for: $file"
              md5sum "$file" | cut -d' ' -f1 > "$file.md5"
            fi
            if [ ! -f "$file.sha1" ]; then
              echo "Generating SHA1 for: $file"
              sha1sum "$file" | cut -d' ' -f1 > "$file.sha1"
            fi
          fi
        done
        
        # Show final bundle contents
        echo "Final bundle contents:"
        ls -la "$ARTIFACT_DIR"
        
        # Show the directory structure that will be in the ZIP
        echo "Bundle directory structure:"
        cd "$BUNDLE_DIR"
        find . -type f | sort
        
        # Create bundle zip from the root of the structure
        zip -r "/tmp/$ARTIFACT_ID-$VERSION-bundle.zip" .
        
        echo "Bundle created at: /tmp/$ARTIFACT_ID-$VERSION-bundle.zip"
        echo "Bundle size: $(ls -lh /tmp/$ARTIFACT_ID-$VERSION-bundle.zip)"
        
        echo "Uploading bundle to Maven Central Portal..."
        UPLOAD_RESPONSE=$(curl -w "HTTP_STATUS:%{http_code}" -X POST \
          -H "Content-Type: multipart/form-data" \
          -F "bundle=@/tmp/$ARTIFACT_ID-$VERSION-bundle.zip" \
          -u "$MAVEN_CENTRAL_USERNAME:$MAVEN_CENTRAL_TOKEN" \
          "https://central.sonatype.com/api/v1/publisher/upload?publishingType=AUTOMATIC")
        
        HTTP_STATUS=$(echo $UPLOAD_RESPONSE | tr -d '\n' | sed -e 's/.*HTTP_STATUS://')
        RESPONSE_BODY=$(echo $UPLOAD_RESPONSE | sed -e 's/HTTP_STATUS:.*//g')
        
        echo "Upload response status: $HTTP_STATUS"
        echo "Upload response body: $RESPONSE_BODY"
        
        if [ $HTTP_STATUS -eq 200 ] || [ $HTTP_STATUS -eq 201 ]; then
          echo "Upload completed successfully!"
        else
          echo "Upload failed with status: $HTTP_STATUS"
          exit 1
        fi
      env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
    - name: Publish Destination locally for example app to use
      run: ./gradlew publishToMavenLocal
    - name: Build Example APK
      run: ./gradlew :example:assembleRelease