name: Android Segment Release
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
env:
  # UPDATED: Use new Maven Central Portal credentials instead of OSSRH
  MAVEN_CENTRAL_USERNAME: "${{ secrets.MAVEN_CENTRAL_USERNAME }}"
  MAVEN_CENTRAL_TOKEN: "${{ secrets.MAVEN_CENTRAL_TOKEN }}"
  # UPDATED: Remove SONATYPE_STAGING_PROFILE_ID as it's not needed for Portal
  SIGNING_KEY: "${{ secrets.GPG_KEY_CONTENTS_BASE64 }}"
  KEY_ID: "${{ secrets.SIGNING_KEY_ID }}"
  KEY_PASSWORD: "${{ secrets.SIGNING_PASSWORD }}"
  KEY_RING_FILE: "secret.kbx"
  TAG_NAME: "${{ inputs.version }}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle # This will automatically cache dependencies
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Download Dependencies
      run: ./gradlew androidDependencies
    - name: Build Destination
      run: ./gradlew clean :destination:build
    - name: Add Maven Central signing key
      run: base64 -d <<< ${{ env.SIGNING_KEY }} > destination/${{ env.KEY_RING_FILE }}
    - name: Upload builds to Maven Central Portal and transfer
      run: |
        echo "Publishing to Maven Central Portal..."
        ./gradlew :destination:publishReleasePublicationToOSSRHRepository --info
        
        echo "Transferring to Central Portal for visibility..."
        curl -X POST \
          -u "$ORG_GRADLE_PROJECT_mavenCentralUsername:$ORG_GRADLE_PROJECT_mavenCentralPassword" \
          "https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/com.segment"
        
        echo "Upload and transfer completed!"
      env:
        # UPDATED: Use Portal credentials instead of OSSRH
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
    - name: Publish Destination locally for example app to use
      run: ./gradlew publishToMavenLocal
    - name: Build Example APK
      run: ./gradlew :example:assembleRelease