name: Segment Release
on:
  # Temporarily changed from workflow_call to push trigger
  push:
    branches:
      - release-test
  # Keep workflow_call for when you want to revert back
  # workflow_call:
  #   inputs:
  #     version:
  #       required: true
  #       type: string
env:
  # Keep original variable names for Gradle compatibility, but use new Portal credentials
  OSSRH_USERNAME: "${{ secrets.MAVEN_CENTRAL_USERNAME }}"
  OSSRH_PASSWORD: "${{ secrets.MAVEN_CENTRAL_TOKEN }}"
  # Temporary: Keep for compatibility until publish-mavencentral.gradle is updated
  SONATYPE_STAGING_PROFILE_ID: ""
  SIGNING_KEY: "${{ secrets.GPG_KEY_CONTENTS_BASE64 }}"
  KEY_ID: "${{ secrets.SIGNING_KEY_ID }}"
  KEY_PASSWORD: "${{ secrets.SIGNING_PASSWORD }}"
  KEY_RING_FILE: "secret.kbx"
  TAG_NAME: "${{ github.ref_name }}" # Changed from inputs.version since we no longer have inputs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle # This will automatically cache dependencies
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Download Dependencies
      run: ./gradlew androidDependencies
    - name: Build Destination
      run: ./gradlew clean :destination:build
    - name: Add Maven Central signing key
      run: base64 -d <<< ${{ env.SIGNING_KEY }} > destination/${{ env.KEY_RING_FILE }}
    - name: Build and publish to Maven Central Portal
      run: |
        echo "Building and signing artifacts..."
        ./gradlew :destination:publishReleasePublicationToMavenLocal --info
        
        echo "Creating bundle for Portal upload..."
        cd ~/.m2/repository/com/userleap/segment-analytics-kotlin-destination/1.2.5/
        zip -r segment-analytics-kotlin-destination-1.2.5-bundle.zip *.pom *.jar *.aar *.asc
        
        echo "Uploading bundle to Maven Central Portal..."
        curl -X POST \
          -H "Content-Type: multipart/form-data" \
          -F "bundle=@segment-analytics-kotlin-destination-1.2.5-bundle.zip" \
          -u "$MAVEN_CENTRAL_USERNAME:$MAVEN_CENTRAL_TOKEN" \
          "https://central.sonatype.com/api/v1/publisher/upload?publishingType=AUTOMATIC"
        
        echo "Upload completed!"
      env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
    - name: Publish Destination locally for example app to use
      run: ./gradlew publishToMavenLocal
    - name: Build Example APK
      run: ./gradlew :example:assembleRelease