name: Android Build & Test

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle # This will automatically cache dependencies

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Download Dependencies
      run: ./gradlew androidDependencies
      
    - name: Run SDK Test
      run: ./gradlew :destination:testDebugUnitTest
      
    - uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: destination/build/test-results
        
    - name: Run SDK Lint
      run: ./gradlew :destination:lint
      
    - uses: actions/upload-artifact@v3
      with:
        name: lint-results
        path: destination/build/reports
      
    - name: Build Segment Destination
      run: ./gradlew :destination:assembleDebug
      
    - name: Build test app APK
      run: ./gradlew :example:assembleDebug

