name: Android Segment Release
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
env:
  # Keep original variable names for Gradle compatibility, but use new Portal credentials
  OSSRH_USERNAME: "${{ secrets.MAVEN_CENTRAL_USERNAME }}"
  OSSRH_PASSWORD: "${{ secrets.MAVEN_CENTRAL_TOKEN }}"
  # Temporary: Keep for compatibility until publish-mavencentral.gradle is updated
  SONATYPE_STAGING_PROFILE_ID: ""
  SIGNING_KEY: "${{ secrets.GPG_KEY_CONTENTS_BASE64 }}"
  KEY_ID: "${{ secrets.SIGNING_KEY_ID }}"
  KEY_PASSWORD: "${{ secrets.SIGNING_PASSWORD }}"
  KEY_RING_FILE: "secret.kbx"
  TAG_NAME: "${{ github.ref_name }}" # Changed from inputs.version since we no longer have inputs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle # This will automatically cache dependencies
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Download Dependencies
      run: ./gradlew androidDependencies
    - name: Build Destination
      run: ./gradlew clean :destination:build
    - name: Add Maven Central signing key
      run: base64 -d <<< ${{ env.SIGNING_KEY }} > destination/${{ env.KEY_RING_FILE }}
    - name: Build and publish to Maven Central Portal
      run: |
        echo "Building and signing artifacts..."
        ./gradlew :destination:publishReleasePublicationToMavenLocal --info
        
        echo "Creating properly structured bundle for Portal upload..."
        # Get the version from Gradle properties or use a default
        VERSION=$(./gradlew -q :destination:printVersion 2>/dev/null || echo "1.2.5")
        GROUP_PATH="com/userleap"
        ARTIFACT_ID="segment-analytics-kotlin-destination"
        
        # Create temporary directory with proper Maven structure
        BUNDLE_DIR="/tmp/maven-bundle"
        ARTIFACT_DIR="$BUNDLE_DIR/$GROUP_PATH/$ARTIFACT_ID/$VERSION"
        mkdir -p "$ARTIFACT_DIR"
        
        # Copy artifacts from local Maven repository
        LOCAL_REPO="$HOME/.m2/repository/$GROUP_PATH/$ARTIFACT_ID/$VERSION"
        cp "$LOCAL_REPO"/*.pom "$ARTIFACT_DIR/"
        cp "$LOCAL_REPO"/*.aar "$ARTIFACT_DIR/" 2>/dev/null || true
        cp "$LOCAL_REPO"/*.jar "$ARTIFACT_DIR/" 2>/dev/null || true
        cp "$LOCAL_REPO"/*.asc "$ARTIFACT_DIR/"
        
        # Generate MD5 and SHA1 checksums for all files
        cd "$ARTIFACT_DIR"
        for file in *.pom *.aar *.jar; do
          if [ -f "$file" ]; then
            md5sum "$file" | cut -d' ' -f1 > "$file.md5"
            sha1sum "$file" | cut -d' ' -f1 > "$file.sha1"
          fi
        done
        
        # Create bundle zip from the root of the structure
        cd "$BUNDLE_DIR"
        zip -r "/tmp/$ARTIFACT_ID-$VERSION-bundle.zip" .
        
        echo "Uploading bundle to Maven Central Portal..."
        curl -X POST \
          -H "Content-Type: multipart/form-data" \
          -F "bundle=@/tmp/$ARTIFACT_ID-$VERSION-bundle.zip" \
          -u "$MAVEN_CENTRAL_USERNAME:$MAVEN_CENTRAL_TOKEN" \
          "https://central.sonatype.com/api/v1/publisher/upload?publishingType=AUTOMATIC"
        
        echo "Upload completed!"
      env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
    - name: Publish Destination locally for example app to use
      run: ./gradlew publishToMavenLocal
    - name: Build Example APK
      run: ./gradlew :example:assembleRelease